# SPDX-FileCopyrightText: 2026 Koen van Greevenbroek
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Write (or check) the provenance stamp of a calibration artefact set.

The stamp records the structural configuration a calibration artefact set
was fit against; see workflow/validation/calibration_provenance.py for
the snapshot semantics. Invoked by ``tools/calibrate`` after a successful
run (and with ``--check`` as part of ``tools/calibrate --check``).

Usage:
    pixi run python workflow/scripts/write_calibration_provenance.py \
        [--base config/<name>.yaml] [--check]
"""

import argparse
from datetime import datetime, timezone
from pathlib import Path
import subprocess
import sys

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from workflow.scripts.solve_namespace import (  # noqa: E402
    load_merged_config,
    resolve_gbd_anchoring,
)
from workflow.validation.calibration_provenance import (  # noqa: E402
    diff_snapshots,
    load_provenance,
    provenance_path,
    structural_snapshot,
)


def _git_commit() -> str | None:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base",
        help="Base config layered on config/default.yaml (default: none)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare the existing stamp against the current config instead of writing",
    )
    parser.add_argument(
        "--print-source",
        action="store_true",
        help="Print the resolved calibration.source and exit (used by tools/calibrate)",
    )
    parser.add_argument(
        "--print-anchoring",
        action="store_true",
        help=(
            "Print the base config's resolved diet.anchor_groups_to_gbd "
            "('true'/'false') and exit (used by tools/calibrate to pin every "
            "calibration step to the base config's baseline diet)"
        ),
    )
    args = parser.parse_args()

    configfiles = [PROJECT_ROOT / "config" / "default.yaml"]
    if args.base:
        configfiles.append(Path(args.base))
    config = load_merged_config(*configfiles)
    source = config["calibration"]["source"]

    if args.print_source:
        print(source)
        return 0

    if args.print_anchoring:
        print("true" if resolve_gbd_anchoring(config) else "false")
        return 0

    snapshot = structural_snapshot(config)

    if args.check:
        try:
            stamp = load_provenance(source, PROJECT_ROOT)
        except ValueError as exc:
            print(exc)
            return 1
        diffs = diff_snapshots(stamp["structural_config"], snapshot)
        if diffs:
            print(f"Provenance MISMATCH for artefact set '{source}':")
            for d in diffs:
                print(f"  {d}")
            return 1
        print(f"Provenance of artefact set '{source}' matches the current config.")
        return 0

    path = provenance_path(source, PROJECT_ROOT)
    path.parent.mkdir(parents=True, exist_ok=True)
    stamp = {
        "source": source,
        "base_config": str(Path(args.base)) if args.base else "config/default.yaml",
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "git_commit": _git_commit(),
        "structural_config": snapshot,
    }
    with open(path, "w") as f:
        f.write(
            "# Provenance stamp of this calibration artefact set: the\n"
            "# structural config it was fit against. Generated by\n"
            "# workflow/scripts/write_calibration_provenance.py via\n"
            "# tools/calibrate; do not edit by hand.\n"
            "# Licensing: see the annotation in REUSE.toml.\n"
        )
        yaml.safe_dump(stamp, f, sort_keys=True, default_flow_style=False)
    print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
