# SPDX-FileCopyrightText: 2026 Koen van Greevenbroek
#
# SPDX-License-Identifier: CC-BY-4.0

name: "opt"

scenarios:
  baseline:
    # Fixed consumption to extract consumer values (dual variables)
    validation:
      enforce_baseline_diet: true
    food_incentives:
      enabled: false
    health:
      value_per_yll: 0
    emissions:
      ghg_price: 0
    # Note: no constraint on caloric intake

  default:
    food_utility_piecewise:
      enabled: true
    health:
      value_per_yll: 5000
    emissions:
      ghg_price: 200
    macronutrients:
      cal:
        equal: 2400  # kcal/person/day

solving:
  solver: "gurobi"
  io_api: "direct"
  threads: 2
