# SPDX-FileCopyrightText: 2026 Koen van Greevenbroek
#
# SPDX-License-Identifier: CC-BY-4.0

name: "opt"

scenarios:
  baseline:
    # Fixed consumption to extract consumer values (dual variables)
    validation:
      enforce_baseline_diet: true
    food_utility_piecewise:
      enabled: false
    health:
      value_per_yll: 0
    emissions:
      ghg_price: 0

  default:
    health:
      value_per_yll: 5000
    emissions:
      ghg_price: 200
    macronutrients:
      cal:
        equal_to_baseline: true

food_utility_piecewise:
  enabled: true

solving:
  solver: "gurobi"
  io_api: "direct"
  threads: 2
