# SPDX-FileCopyrightText: 2025 Koen van Greevenbroek
#
# SPDX-License-Identifier: CC-BY-4.0

name: "validation"
scenarios:
  default: {}
  uncalibrated:
    grazing:
      grassland_forage_calibration:
        enabled: false

planning_horizon: 2020

validation:
  use_actual_yields: true
  use_actual_production: true
  enforce_baseline_diet: true
  enforce_baseline_feed: true
  disable_spared_cropland: true
  disable_spared_grassland: true
  slack_marginal_cost: 10

cost_calibration:
  enabled: false

grazing:
  grassland_forage_calibration:
    generate: true
    scenario: uncalibrated

# macronutrients:
#   cal:
#     min: 2400

health:
  enabled: false

emissions:
  ghg_pricing_enabled: false

solving:
  io_api: "direct"
  solver: "highs"
  threads: 2
  # options_gurobi:
  #   DualReductions: 0
